# Generated by Django 2.2 on 2020-10-18 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logregapp', '0002_auto_20201018_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='confirm_PW',
        ),
    ]
