# Generated by Django 2.2 on 2020-10-22 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optionNapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Posts',
        ),
    ]
