# Generated by Django 2.2 on 2020-10-20 22:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optionGapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quotes',
            new_name='Quote',
        ),
        migrations.RenameField(
            model_name='quote',
            old_name='quotes',
            new_name='quote',
        ),
    ]
