# Generated by Django 2.2 on 2020-10-20 23:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optionGapp', '0002_auto_20201020_1542'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quote',
            new_name='Quotes',
        ),
    ]
