# Generated by Django 2.2 on 2020-10-21 00:40

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('optionGapp', '0003_auto_20201020_1640'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quotes',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='quotes',
            name='user_quotes',
            field=models.ForeignKey(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_quotes', to='optionGapp.User'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quotes',
            name='author',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='quote',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=45),
        ),
    ]
