# Generated by Django 2.2 on 2020-10-21 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optionGapp', '0005_auto_20201020_2157'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotes',
            old_name='created_by',
            new_name='createdby',
        ),
    ]
