# Generated by Django 2.2 on 2020-10-21 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optionGapp', '0006_auto_20201020_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotes',
            name='createdby',
        ),
    ]
