# Generated by Django 2.2 on 2020-10-21 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optionGapp', '0007_remove_quotes_createdby'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotes',
            name='creator',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='has_created_quotes', to='optionGapp.User'),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='liked_by',
            field=models.ManyToManyField(default=None, related_name='liked_quotes', to='optionGapp.User'),
        ),
    ]
