# Generated by Django 2.2 on 2020-10-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optionGapp', '0008_auto_20201020_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='liked_by',
            field=models.ManyToManyField(related_name='liked_quotes', to='optionGapp.User'),
        ),
    ]
