# Generated by Django 2.2 on 2020-10-21 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('optionGapp', '0009_auto_20201020_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotes',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='has_created_quotes', to='optionGapp.User'),
        ),
        migrations.AlterField(
            model_name='quotes',
            name='updated_at',
            field=models.DateField(auto_now=True),
        ),
    ]
