# Generated by Django 2.2 on 2020-09-28 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dojo_ninjas_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ninja',
            name='dojo',
            field=models.ForeignKey(default='Best Dojo', on_delete=django.db.models.deletion.CASCADE, related_name='ninja', to='dojo_ninjas_app.Dojo'),
            preserve_default=False,
        ),
    ]
